apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/eks-auto-mode
  - ../../base/roles/platform/namespaces
  - ../../base/roles/platform/network-policies
  - ../../base/roles/platform/kyverno
  - ../../base/vault
  - ../../base/external-secrets
  - ../../base/roles/platform/istio-security
  - tailscale-platform-access.yaml
