apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../network-policies
patches:
  - patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: execution-only
        namespace: execution
    target:
      kind: NetworkPolicy
      namespace: execution
