apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/eks-auto-mode
  - ../../base/roles/execution/namespaces
  - ../../base/runtime-classes
  - ../../base/quotas
  - ../../base/roles/execution/network-policies
  - ../../base/roles/execution/kyverno
  - ../../base/roles/execution/istio-security
  - ../../base/external-secrets
patches:
  - path: patches/execution-namespace-labels.yaml
